#!/bin/sh

echo "Setting up your dotfiles..."

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm ~/.gitconfig
ln -s ~/.dotfiles/dotfiles/git/.gitconfig ~/.gitconfig

# if [[ $? > 0 ]]; then
#   echo 'Error while creating symlink'
# fi
